spring.application.name=api

# Supabase PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.zjmyhgbrvkdnjasxvzrc
spring.datasource.password=quan@nam3_202526
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.web=DEBUG
